### ISSUE TITLE
Can I quote your picture about RNN  in my paper？

### ISSUE THREAD

**Issue by ElvisRain** [colah/colah.github.io#47]
https://camo.githubusercontent.com/90667bfb975db1e7ab28e6a176e722a9820205b2c3d0a912fae312b15477b46f/68747470733a2f2f636f6c61682e6769746875622e696f2f706f7374732f323031352d30382d556e6465727374616e64696e672d4c53544d732f696d672f4c53544d332d7661722d4752552e706e67
The picture you drawed is very fancy. can I use it to introduce RNN in my paper ?  Thank you very much.

**Comment by colah** [comment]
Sure.

**Comment by ElvisRain** [comment]
Thank you ，it helps a lot!

**Comment by nk-fouque** [comment]
@colah Your illustrations are all really good, a lot of people are willing to reuse them, you should probably put some guidelines for reuse/attribution somewhere on the site
Maybe even a license like CC0, CC-BY or anything that you find appropriate
